### ISSUE TITLE
Fatal error response

### ISSUE THREAD

**Issue by uultimoo** [shettyg/ovn-docker#13]
Hello, my intention is to create an overlay network with ovn docker integration. I followed the instructions on two real machine (NO VM) but when i run 

`docker network create -d openvswitch --subnet=192.168.1.0/24 foo` 

on the host i have the fatal error like this:

**Error response from daemon: remote: create_network: lswitch-add Fatal error executing ['ovn-nbctl', '--timeout=5', '-vconsole:off', '--db=tcp:192.168.178.20:6640', 'lswitch-add', u'fca6199e4d317eea5d0b82d5a1375b459bfb5be7de3c48d9d7211f5b1f2e2273', '--', 'set', 'Logical_Switch', u'fca6199e4d317eea5d0b82d5a1375b459bfb5be7de3c48d9d7211f5b1f2e2273', u'external_ids:subnet=192.168.1.0/24', u'external_ids:gateway_ip=192.168.1.1']**

and network creation failed. Could you help me?

**Comment by shettyg** [comment]
@uultimoo 
Are you using openvswitch master? Please use openvswitch branch2.5 (which is a released version) instead of master. The master changes very fast and likely has some bugs.

**Comment by uultimoo** [comment]
Ok. First of all thank You for your answer.I Will try to use branch 2.5. I used wget command reported in the install-ovn.sh. Last question :should i use ovn-docker from this branch or i can use ovn that i find in ovs original folder? Thank you

**Comment by shettyg** [comment]
Please use the openvswitch repository exclusively.

**Comment by uultimoo** [comment]
With Branch2.5. The problem is resolved. Thank you for all.

**Comment by shettyg** [comment]
I think it should work with master too now. The instructions are a little different and has been updated in the openvswitch repo for INSTALL.Docker.md
