### ISSUE TITLE
something wrong in ovn-docker documents

### ISSUE THREAD

**Issue by thnam91** [shettyg/ovn-docker#15]
Hello, I'm a student from South Korea.
I want to build ovn-docker environments. So I followed your documents. But in [ovn-docker/backend.md](https://github.com/shettyg/ovn-docker/blob/master/docs/backend.md), I faced some error messages about module. When I typed 'insmod ./datapath/linux/openvswitch.ko', insmod error occured.

Following is a error messages.

root@ubuntu:~/ovs/datapath/linux# insmod openvswitch.ko
insmod: ERROR: could not insert module openvswitch.ko: Unknown symbol in module

Could you tell me how to solve this problem?

Additionally, I want to get some guide for building ovn-docker environment in my host. I already read official guide in [ovs repository](https://github.com/openvswitch/ovs/blob/master/INSTALL.Docker.md). However, I couldn't understand exactly. Finally, I try it again using your vagrant files.

**Comment by shettyg** [comment]
> root@ubuntu:~/ovs/datapath/linux# insmod openvswitch.ko
> insmod: ERROR: could not insert module openvswitch.ko: Unknown symbol in module

The backend docs were a little stale. You will now need
rmmod openvswitch
modprobe libcrc32c
modprobe nf_conntrack_ipv6
modprobe nf_nat_ipv6
modprobe gre
insmod ./datapath/linux/openvswitch.ko
insmod ./datapath/linux/vport-geneve.ko
