### ISSUE TITLE
Set the mac address of OVS bridge to that of physical NIC

### ISSUE THREAD

**Issue by shettyg** [shettyg/ovn-docker#7]
When 'ovn-integrate nics-to-bridge eth0' is called inside the VM, the newly created 'breth0' can have a different mac than that of 'eth0' for macs created by libvirt. So we need to set:

ovs-vsctl set bridge breth0 other_config:hwaddr="fa:16:3e:0c:31:31"

**Comment by juanpincel** [comment]
In your network configuration `/etc/config/network` you can put the following lines: 

```
config interface 'wan'
        option ifname 'eth0.1'
        option proto 'dhcp'
        option macaddr '00:0C:42:D0:E8:A1'   
```

in the line `option macaddr` you can put the mac address you want.
